#! /usr/bin/env bash

# This script is taken from Michael Adam's demo script
# From the SENG 475 example project repository.

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"

editor_program="$cmd_dir/editor"

echo "Running editor program"
$editor_program || panic "editor program failed"